### ISSUE TITLE
Handle connection drop

### ISSUE THREAD

**Issue by alexwohlbruck** [alexwohlbruck/covalent#23]
If the connection drops to the lamp, it should attempt to auto reconnect on an interval after about 5-10 attempts. If it still fails, then it should fallback to setup mode.

**Comment by alexwohlbruck** [comment]
```
#ff0090
Sending PONG
Connection closed
Reconnecting to server (Attempt 0)
Unhandled exception in thread started by <bound_method>
Traceback (most recent call last):
  File "app/server.py", line 35, in listen
  File "app/server.py", line 65, in reconnect
  File "app/server.py", line 19, in connect
  File "app/uwebsockets/client.py", line 23, in connect
  File "app/uwebsockets/protocol.py", line 42, in urlparse
RuntimeError: maximum recursion depth exceeded
motion = 1
```

**Comment by alexwohlbruck** [comment]
uPy error traceback #2

```
motion = 0
motion = 1
Unhandled exception in thread started by <bound_method>
Traceback (most recent call last):
  File "app/server.py", line 33, in listen
  File "app/uwebsockets/protocol.py", line 184, in recv
  File "app/uwebsockets/protocol.py", line 91, in read_frame
OSError: [Errno 104] ECONNRESET
motion = 0
Failed to send data: {"name": "SEND_LAMP_COMMAND", "data": {"lampId": "624cc0e6168796dd6d614190", "state": {"color": "#ff0000", "touching": false}}}
Failed to send data: {"name": "SEND_LAMP_COMMAND", "data": {"lampId": "624cc0e6168796dd6d614190", "state": {"color": "#ff0000", "touching": true}}}
Failed to send data: {"name": "SEND_LAMP_COMMAND", "data": {"lampId": "624cc0e6168796dd6d614190", "state": {"color": "#ff0000", "touching": false}}}
motion = 1
motion = 0
motion = 1
```
